services:
  order-app:
    build:
      context: ./order
      dockerfile: docker/multi-stage-with-cache.Dockerfile
    depends_on:
      - postgresql
    environment:
      DSN: postgresql://order_user:order_password@postgresql:5432/order_db
    ports:
      - "8085:8080"
    restart: unless-stopped

  postgresql:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data #TODO: переделать на volume
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
      POSTGRES_DB: order_db
    ports:
      - "5435:5432"
    restart: unless-stopped
